
remote_theme: pages-themes/cayman@v0.2.0
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one

title: [Improving Underwater Visual Tracking With a Large Scale Dataset and Image Enhancement]
description: [## Basit Alawode<sup>1</sup>, Sajid Javed<sup>1</sup>, Fayaz Ali Dharejo<sup>1</sup>, Mehnaz Ummar<sup>1</sup>, Arif Mahmood<sup>2</sup>, Naoufel Werghi<sup>1</sup>, Fahad Shahbaz Khan<sup>3</sup>, and Jiri Matas<sup>4</sup>.

### <sup>1</sup>EECS Department, Khalifa University of Science and Technology, Abu Dhabi.
### <sup>2</sup>....
### <sup>3</sup>Computer Vision Department, MBZUAI, Abu Dhabi, UAE.
### <sup>4</sup>Center for Machine Perception, Czech Technical University, Prague.]

show_downloads: true
